Repository TImeCAlling/TImeCAlling_FE, pull requests merged in 2025-02, with the labels that each got.

#48 [Feat/#44] 마이페이지 내정보 api
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/umc/timeCAlling/data/datasource/MypageDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/MypageDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/mypage/UpdateUserRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/mypage/DeleteUserResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/mypage/GetUserResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/mypage/UpdateUserResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/MypageRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/MypageService.kt
  app/src/main/java/com/umc/timeCAlling/di/DataSourceModule.kt
  app/src/main/java/com/umc/timeCAlling/di/RepositoryModule.kt
  app/src/main/java/com/umc/timeCAlling/di/ServiceModule.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/mypage/UpdateUserRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/mypage/DeleteUserResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/mypage/GetUserResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/mypage/UpdateUserResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/MypageRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MyprofileFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/adapter/MyprofileViewModel.kt
  app/src/main/java/com/umc/timeCAlling/util/network/UiState.kt
  app/src/main/res/drawable/shape_rect_999_trans_fill.xml
  app/src/main/res/layout/fragment_myprofile.xml
  app/src/main/res/navigation/main_graph.xml
Labels: 💫 FEAT, 👧 반희

#46 [Feat/#37] 특정 날짜 일정 조회
  .idea/deploymentTargetSelector.xml
  afdfasdfsaf
  app/src/main/java/com/umc/timeCAlling/data/datasource/ChecklistDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasource/ScheduleDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/ChecklistDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/ScheduleDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/checklist/UpdateChecklistRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/checklist/UpdateChecklistResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/MeetTimeResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/ScheduleByDateResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/SchedulesResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/SuccessRateResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/TodayScheduleResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/TodaySchedulesResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/ChecklistRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/ScheduleRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/ChecklistService.kt
  app/src/main/java/com/umc/timeCAlling/data/service/ScheduleService.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/checklist/UpdateChecklistRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/CategoriesResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/UpdateChecklistResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/MeetTimeResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/ScheduleByDateResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/SchedulesResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/SuccessRateResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/TodayScheduleResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/TodaySchedulesResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/ChecklistRepository.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/ScheduleRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/MainActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/DetailScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/ScheduleViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeViewModel.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: 💫 FEAT, 🧑 마르코

#45 [Feat/#42] 일정 생성 api 연결
  app/src/main/java/com/umc/timeCAlling/data/datasource/ScheduleDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/ScheduleDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/CategoriesRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/schedule/ScheduleRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/CreateScheduleResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/ScheduleResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/ScheduleRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/ScheduleService.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/CategoriesRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/schedule/ScheduleRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/CreateScheduleResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/ScheduleResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/ScheduleRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleSecondFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleSuccessFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/util/AuthIntercepter.kt
  app/src/main/res/layout/fragment_add_schedule_second.xml
  app/src/main/res/layout/fragment_add_schedule_success.xml
  app/src/main/res/navigation/main_graph.xml
Labels: 💫 FEAT, 👦루카스

#51 [Feat/#47] 홈 화면 오늘 일정 조회
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/umc/timeCAlling/data/datasource/ScheduleDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/CategoriesByDateResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/ScheduleByDateResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/service/ScheduleService.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/CategoriesByDateResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/ScheduleByDateResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/ScheduleRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/MainActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/DetailScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/ScheduleViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/adapter/TodayScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/LoginFragment.kt
  app/src/main/res/layout/fragment_calendar.xml
Labels: 💫 FEAT, 🧑 마르코

#55 [UI/#53] 마이페이지 xml
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MypageFragment.kt
  app/src/main/res/drawable/ic_mypage_arrow_right.xml
  app/src/main/res/drawable/ic_mypage_face.xml
  app/src/main/res/drawable/shape_mypage_bottom.xml
  app/src/main/res/drawable/shape_rect_16_white_fill.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: ✍️ UI, 🧑 마르코

#52 [Feat/#43] 토큰 갱신 api
  app/build.gradle.kts
  app/src/main/java/com/umc/timeCAlling/TimeCAllingApplication.kt
  app/src/main/java/com/umc/timeCAlling/data/datasource/LoginDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/LoginDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/login/TokenRefreshRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/login/TokenRefreshResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/LoginRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/LoginService.kt
  app/src/main/java/com/umc/timeCAlling/di/NetworkModule.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/login/TokenRefreshRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/login/TokenRefreshResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/LoginRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/LoginFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/util/AuthIntercepter.kt
Labels: 💫 FEAT, 👧 반희

#56 [UI/#54] 마이페이지 음성정보 UI
  app/src/main/java/com/umc/timeCAlling/presentation/login/LoginFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MypageVoiceFragment.kt
  app/src/main/res/drawable/custom_seekbar_progress.xml
  app/src/main/res/drawable/ic_check_mint.xml
  app/src/main/res/drawable/shape_rect_999_gray400_fill.xml
  app/src/main/res/drawable/shape_rect_999_white_fill_mint_shadow.xml
  app/src/main/res/layout/fragment_mypage_voice.xml
  app/src/main/res/navigation/main_graph.xml
Labels: ✍️ UI, 👧 반희

#60 [Feat/#57] 공유하기 url 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/timeCAlling/data/datasource/ScheduleDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/ScheduleDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/login/TokenRefreshResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/CreateScheduleResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/SharedScheduleResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/ScheduleRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/ScheduleService.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/login/TokenRefreshResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/CreateScheduleResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/SharedScheduleResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/ScheduleRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/MainActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleSecondFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleSuccessFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/CategoryEditFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/CategoryManager.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/LocationSearchFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/adapter/CategoryEditRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/adapter/CategoryRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/LoginFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/util/AuthIntercepter.kt
  app/src/main/res/drawable/shape_rect_10_gray300_fill_gray400_line_1.xml
  app/src/main/res/layout/dialog_schedule_share.xml
  app/src/main/res/layout/fragment_add_schedule.xml
  app/src/main/res/layout/fragment_add_schedule_second.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/strings.xml
Labels: 💫 FEAT, 👦루카스

#59 [UI/#53] 알람리스트 UI 작업
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/alarmlist/AddAlarmFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/alarmlist/AlarmlistFragment.kt
  app/src/main/res/drawable/ic_add_alarm_arrow_down.xml
  app/src/main/res/drawable/ic_add_alarm_arrow_up.xml
  app/src/main/res/drawable/ic_add_alarm_time.xml
  app/src/main/res/drawable/ic_alarmlist_add.xml
  app/src/main/res/drawable/ic_alarmlist_delete.xml
  app/src/main/res/drawable/ic_alarmlist_mail.xml
  app/src/main/res/drawable/shape_rect_16_gray200_fill_gray300_line_1.xml
  app/src/main/res/layout/fragment_add_alarm.xml
  app/src/main/res/layout/fragment_alarmlist.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_last_schedule.xml
  app/src/main/res/navigation/main_graph.xml
Labels: ✍️ UI, 🧑 마르코

#63 [Feat/#61] 알람 울리기 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/timeCAlling/TimeCAllingApplication.kt
  app/src/main/java/com/umc/timeCAlling/presentation/MainActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleSecondFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/alarm/AlarmActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/alarm/AlarmHelper.kt
  app/src/main/java/com/umc/timeCAlling/presentation/alarm/AlarmReceiver.kt
  app/src/main/res/navigation/main_graph.xml
Labels: 💫 FEAT, 👦루카스

#65 [FEAT/#62] API 연결 완
  app/src/main/java/com/umc/timeCAlling/data/datasource/ScheduleDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/ScheduleDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/MeetTimeResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/CategoriesByDetailResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/DetailScheduleResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/MeetTimeResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/ScheduleStatusResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/ScheduleRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/ScheduleService.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/CategoriesByDetailResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/DetailScheduleResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/MeetTimeResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/ScheduleStatusResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/ScheduleRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/DetailScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/ScheduleViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/adapter/DetailScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/adapter/TodayScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/LoginFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MypageFragment.kt
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_today_schedule.xml
  app/src/main/res/layout/item_today_schedule_detail.xml
Labels: 💫 FEAT, 🧑 마르코

#74 [Fix/#72] tmap token 오류
  app/src/main/java/com/umc/timeCAlling/di/NetworkModule.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/LoginFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupSpareFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/alarmlist/AlarmlistFragment.kt
  app/src/main/java/com/umc/timeCAlling/util/AuthIntercepter.kt
  app/src/main/java/com/umc/timeCAlling/util/TokenAuthenticator.kt
  app/src/main/res/layout/fragment_add_alarm.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_alarmlist.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/appearances.xml
Labels: 🔧FIX, 👧 반희

#70 [Feat/#68] 깨우기 알람 보내기 구현
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/timeCAlling/MyFirebaseMessagingService.kt
  app/src/main/java/com/umc/timeCAlling/data/datasource/AlarmDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/AlarmDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/FcmTokenDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/alarm/FcmTokenRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/alarm/WakeUpAlarmRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/alarm/FcmTokenResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/alarm/WakeUpAlarmResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/ScheduleUsersResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/AlarmRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/AlarmService.kt
  app/src/main/java/com/umc/timeCAlling/di/NetworkModule.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/FcmTokenModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/alarm/FcmTokenRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/alarm/WakeUpAlarmRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/alarm/FcmTokenResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/alarm/WakeUpAlarmResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/ScheduleUsersResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/AlarmRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/alarm/AlarmActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/ScheduleViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/wakeup/WakeupFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/wakeup/WakeupPeopleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/wakeup/WakeupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupViewModel.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 💫 FEAT, 👦루카스

#71 [Feat/#50] 마이페이지 내정보 updateuser api 연결
  app/src/main/java/com/umc/timeCAlling/data/datasource/MypageDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/MypageDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/mypage/UpdateUserRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/MypageRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/MypageService.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/mypage/UpdateUserRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/MypageRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupPhotoFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MyprofileFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/adapter/MyprofileViewModel.kt
  app/src/main/res/drawable/ic_profile_default.xml
  app/src/main/res/drawable/ic_profile_default_default.png
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_myprofile.xml
  app/src/main/res/layout/fragment_signup_photo.xml
Labels: 💫 FEAT, 👧 반희

#77 [Fix/#76] 알람 view 수정 및 리팩토링
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleSecondFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleSuccessFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/LocationSearchFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/adapter/DetailScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/wakeup/WakeupFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/checkList/CheckListFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MypageFragment.kt
  app/src/main/res/drawable/ic_wakeup_none.png
  app/src/main/res/layout/fragment_add_schedule_second.xml
  app/src/main/res/layout/fragment_add_schedule_success.xml
  app/src/main/res/layout/fragment_wakeup.xml
  app/src/main/res/layout/item_today_schedule_detail.xml
  app/src/main/res/values/themes.xml
Labels: 🔧FIX, 👦루카스

#81 [FIX/#80] 자잘한 부분 수정..
  app/src/main/java/com/umc/timeCAlling/data/datasource/ScheduleDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/ScheduleDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/PastScheduleListResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/schedule/PastScheduleResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/ScheduleRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/ScheduleService.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/PastScheduleListResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/schedule/PastScheduleResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/ScheduleRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/ScheduleViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/adapter/DetailScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/wakeup/WakeupFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/adapter/TodayScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MypageFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_schedule_member.xml
  app/src/main/res/navigation/main_graph.xml
Labels: 🔧FIX, 🧑 마르코

#82 [Fix/#79] 데모데이 fcm 재발급 토큰
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/umc/timeCAlling/MyFirebaseMessagingService.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleSecondFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/alarm/AlarmActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/alarm/AlarmHelper.kt
  app/src/main/java/com/umc/timeCAlling/presentation/alarm/AlarmReceiver.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/adapter/MyprofileViewModel.kt
  app/src/main/java/com/umc/timeCAlling/util/TokenRefreshWorker.kt
  app/src/main/res/layout/activity_alarm.xml
  gradle/libs.versions.toml
Labels: 🔧FIX, 💫 FEAT, 👦루카스
