Repository TImeCAlling/TImeCAlling_FE, pull requests merged in 2025-01, with the labels that each got.

#6 [CHORE/#5] icon 추가
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_icon.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/ic_trash.xml
Labels: 🖱️CHORE, 👦루카스

#8 [Chore/#5] 기본세팅 끝내기
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_icon.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/ic_trash.xml
Labels: 🖱️CHORE, 👦루카스

#18 [Chore/#17] 바텀네비 UI 수정
  app/src/main/java/com/umc/timeCAlling/presentation/MainActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleFragment.kt
  app/src/main/res/drawable/bottom_nav_shadow.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/main_menu.xml
Labels: 🖱️CHORE, ➕ADD, 👧 반희

#25 [Fix/#24] main브랜치 오류 해결
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup1/OnboardingActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup1/OnboardingNameActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup1/OnboardingPhotoActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup1/OnboardingSpareActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup1/OnboardingTermActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup1/OnboardingTimeActivity.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_onboarding_name.xml
  app/src/main/res/layout/activity_onboarding_photo.xml
  app/src/main/res/layout/activity_onboarding_spare.xml
  app/src/main/res/layout/activity_onboarding_term.xml
  app/src/main/res/layout/activity_onboarding_time.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/appearances.xml
Labels: 🔧FIX, 👧 반희

#28 [UI/#22] 체크리스트 + 준비중 화면 xml 작성
  app/src/main/java/com/umc/timeCAlling/TopSheetBehavior.java
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/DetailScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/checkList/CheckListFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/checkList/CheckListResultFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/checkList/QuestionItem.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/adapter/LastScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/adapter/TodayScheduleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup/SignupFragment.kt
  app/src/main/res/drawable/circle_progressbar.xml
  app/src/main/res/drawable/ic_arrow_right_gray400.xml
  app/src/main/res/drawable/ic_checklist_smile.png
  app/src/main/res/drawable/ic_icon_mint_fill.xml
  app/src/main/res/drawable/ic_pre_alarm.xml
  app/src/main/res/drawable/ic_pre_rest.xml
  app/src/main/res/drawable/img_checklist_result.png
  app/src/main/res/drawable/shape_rect_18_white_fill_gray300_line_1.xml
  app/src/main/res/drawable/shape_rect_20_gray200_fill.xml
  app/src/main/res/drawable/shape_rect_20_mint300_fill_mint_line_1.xml
  app/src/main/res/drawable/shape_rect_26_mint300_fill.xml
  app/src/main/res/drawable/shape_top_sheet.xml
  app/src/main/res/drawable/top_sheet_handle.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_check_list.xml
  app/src/main/res/layout/fragment_check_list_result.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_checklist_answer.xml
  app/src/main/res/layout/item_checklist_answer2.xml
  app/src/main/res/layout/item_last_schedule.xml
  app/src/main/res/layout/item_today_schedule_detail.xml
  app/src/main/res/layout/layout_home_top_sheet.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/appearances.xml
Labels: ✍️ UI, 🧑 마르코

#27 [UI/#26] 공유하기 xml 제작
  app/build.gradle.kts
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleSecondFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/AddScheduleViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/CategoryEditFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/CategoryManager.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/adapter/CategoryEditRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/addSchedule/adapter/CategoryRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/alarm/AlarmActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/wakeup/WakeupFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/wakeup/WakeupPeopleRVA.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MyprofileFragment.kt
  app/src/main/res/drawable/bg_alarm.png
  app/src/main/res/drawable/ic_alarm_black.xml
  app/src/main/res/drawable/ic_alarm_stop.xml
  app/src/main/res/drawable/ic_bell.xml
  app/src/main/res/drawable/ic_calendar_black.xml
  app/src/main/res/drawable/ic_repeat.xml
  app/src/main/res/drawable/ic_share_circle.xml
  app/src/main/res/drawable/img_alarm.png
  app/src/main/res/drawable/img_people_profile_example.png
  app/src/main/res/drawable/img_people_profile_example2.jpg
  app/src/main/res/drawable/img_people_profile_example3.png
  app/src/main/res/drawable/img_people_profile_example4.png
  app/src/main/res/drawable/img_people_profile_example5.png
  app/src/main/res/drawable/shape_rect_16_mint_fill_shadow.xml
  app/src/main/res/drawable/shape_rect_20_mint200_fill.xml
  app/src/main/res/drawable/shape_rect_30_0_white_fill.xml
  app/src/main/res/drawable/shape_rect_999_gray900_fill.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/dialog_wakeup.xml
  app/src/main/res/layout/dialog_wakeup_share.xml
  app/src/main/res/layout/fragment_add_schedule.xml
  app/src/main/res/layout/fragment_add_schedule_second.xml
  app/src/main/res/layout/fragment_myprofile.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_wakeup.xml
  app/src/main/res/layout/item_bottom_sheet_category.xml
  app/src/main/res/layout/item_wakeup_people.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ✍️ UI, 👦루카스

#35 [UI/#32] 마이페이지 나머지 UI 작업
  app/src/main/java/com/umc/timeCAlling/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/mypage/MyprofileFragment.kt
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_calendar_date.xml
  app/src/main/res/layout/item_today_schedule_detail.xml
  app/src/main/res/layout/layout_withdraw_account_dialog.xml
Labels: 🖱️CHORE, ✍️ UI, 🧑 마르코

#41 [Feat/#40] 로그인 회원가입 api 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/timeCAlling/TimeCAllingApplication.kt
  app/src/main/java/com/umc/timeCAlling/data/datasource/LoginDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/LoginDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/login/KakaoLoginRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/login/KakaoSignupRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/login/KakaoLoginResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/login/KakaoSignupResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/LoginRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/LoginService.kt
  app/src/main/java/com/umc/timeCAlling/di/DataSourceModule.kt
  app/src/main/java/com/umc/timeCAlling/di/NetworkModule.kt
  app/src/main/java/com/umc/timeCAlling/di/RepositoryModule.kt
  app/src/main/java/com/umc/timeCAlling/di/ServiceModule.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/login/KakaoLoginRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/login/KakaoSignupRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/login/KakaoLoginResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/login/KakaoSignupResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/LoginRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/SplashActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/LoginFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupCompleteFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupNameFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupPhotoFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupSpareFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupTermFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupTimeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupTimeAdapter.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup/SignupFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup/SignupPhotoFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup/SignupTimeViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup/SignupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/util/AuthIntercepter.kt
  app/src/main/res/drawable/bg_signup_rv_1.xml
  app/src/main/res/drawable/bg_signup_rv_2.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_myprofile.xml
  app/src/main/res/layout/fragment_signup_complete.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_signup_photo.xml
  app/src/main/res/layout/fragment_signup_spare.xml
  app/src/main/res/layout/fragment_signup_term.xml
  app/src/main/res/layout/fragment_signup_time.xml
  app/src/main/res/navigation/main_graph.xml
  settings.gradle.kts
Labels: 💫 FEAT, 👦루카스

#38 [Feat/#36] 카카오 로그인 api 연결하기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/timeCAlling/TimeCAllingApplication.kt
  app/src/main/java/com/umc/timeCAlling/data/datasource/LoginDataSource.kt
  app/src/main/java/com/umc/timeCAlling/data/datasourceImpl/LoginDataSourceImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/login/KakaoLoginRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/request/login/KakaoSignupRequestDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/login/KakaoLoginResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/dto/response/login/KakaoSignupResponseDto.kt
  app/src/main/java/com/umc/timeCAlling/data/repositoryImpl/LoginRepositoryImpl.kt
  app/src/main/java/com/umc/timeCAlling/data/service/LoginService.kt
  app/src/main/java/com/umc/timeCAlling/di/DataSourceModule.kt
  app/src/main/java/com/umc/timeCAlling/di/NetworkModule.kt
  app/src/main/java/com/umc/timeCAlling/di/RepositoryModule.kt
  app/src/main/java/com/umc/timeCAlling/di/ServiceModule.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/login/KakaoLoginRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/request/login/KakaoSignupRequestModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/login/KakaoLoginResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/model/response/login/KakaoSignupResponseModel.kt
  app/src/main/java/com/umc/timeCAlling/domain/repository/LoginRepository.kt
  app/src/main/java/com/umc/timeCAlling/presentation/SplashActivity.kt
  app/src/main/java/com/umc/timeCAlling/presentation/home/HomeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/LoginFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupCompleteFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupNameFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupPhotoFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupSpareFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupTermFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/SignupTimeFragment.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/LoginViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupTimeAdapter.kt
  app/src/main/java/com/umc/timeCAlling/presentation/login/adapter/SignupViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup/SignupTimeViewModel.kt
  app/src/main/java/com/umc/timeCAlling/presentation/signup/SignupViewModel.kt
  app/src/main/res/drawable/bg_signup_rv_1.xml
  app/src/main/res/drawable/bg_signup_rv_2.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_myprofile.xml
  app/src/main/res/layout/fragment_signup_complete.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_signup_photo.xml
  app/src/main/res/layout/fragment_signup_spare.xml
  app/src/main/res/layout/fragment_signup_term.xml
  app/src/main/res/layout/fragment_signup_time.xml
  app/src/main/res/navigation/main_graph.xml
  settings.gradle.kts
Labels: 💫 FEAT, 👧 반희
